### PR TITLE
Proposal for new version naming standard

### PR DESCRIPTION
**Pull request by MisterSheeple**
Here's a work in progress PR for implementing Omniarchive's version naming standard. This lays the groundwork for eventually adding Omniarchive versions into the launcher by updating existing versions to fit the standards of the rest. This standard aims to make names as consistent as possible by increasing specificity and removing as many inconsistencies as possible.

Some of the changes introduced include:

- Versions that share the same name now have release times appended to the ends of their names as `-HHMM` or `-HHMMSS`.
- Versions that differ between their launcher versions and their original pre-launcher versions have `-launcher` appended to the ends of their names.
	- 0.30 slightly breaks this rule, as it had a renew before it was even in the launcher, so this version is called `c0.30-c-renew`.
- A few versions that are mislabeled duplicates of other versions are deleted.

TO DO:

- [x] Update release versions to new name system
- [x] Delete duplicate releases
- [ ] Update pre-release/snapshot versions to new name system
- [ ] Delete duplicate pre-releases/snapshots, if any exist
- [ ] Update index.json to accommodate for the changes

Feedback would be greatly appreciated. I apologize if there's any mistakes, but I'm pretty sure there aren't any.

### CODE REVIEW

**Comment by jopejoe1** [comment]
Changes should be made in https://github.com/PrismLauncher/meta as any changes made here would be overriden at the next automated update.

**Comment by MisterSheeple** [comment]
Okay thanks

**Comment by jopejoe1** [comment]
If you need any help with that i can do some work on that tommorow when i wake up.

**Comment by MisterSheeple** [comment]
That would be greatly appreciated, thanks! I'll give it a go tomorrow as
well

**Pull request closed without merging**
